- project:
    check:
      jobs:
        - watcher-tempest-zuulv3
        - watcher-tempest-dummy_optim
        - watcher-tempest-actuator
        - watcher-tempest-basic_optim
        - watcher-tempest-workload_balancing

    gate:
      jobs:
        - watcher-tempest-zuulv3
        - watcher-tempest-dummy_optim
        - watcher-tempest-actuator
        - watcher-tempest-basic_optim
        - watcher-tempest-workload_balancing

