- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - watcher-tempest-functional
        - watcher-tempest-dummy_optim:
            voting: false
        - watcher-tempest-actuator:
            voting: false
        - watcher-tempest-basic_optim:
            voting: false
        - watcher-tempest-vm_workload_consolidation:
            voting: false
        - watcher-tempest-host_maintenance:
            voting: false
        - watcher-tempest-storage_balance:
            voting: false
        - watcher-tempest-workload_balancing:
            voting: false
        - watcher-tempest-zone_migration:
            voting: false

    gate:
      queue: watcher
      jobs:
        - watcher-tempest-functional

