- project:
    check:
      jobs:
        - watcher-tempest-functional:
            voting: false
        - watcher-tempest-dummy_optim:
            voting: false
        - watcher-tempest-actuator:
            voting: false
        - watcher-tempest-basic_optim:
            voting: false
        - watcher-tempest-workload_balancing:
            voting: false
        - watcher-tempest-zone_migration

    gate:
      jobs:
        - watcher-tempest-zone_migration

- job:
    name: watcher-tempest-zone_migration
    parent: watcher-tempest-multinode
    vars:
      tempest_test_regex: 'watcher_tempest_plugin.tests.scenario.test_execute_zone_migration'
